name: Mi Primer Workflow


on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el Repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: las dependencias se isntalaran
        run: npm install

      - name: Ejecutar Pruebas
        run: npm test 
